/*
 *  runaround.h
 *  joe2
 *
 * created by wolfgang 
 */
/*-----------------------------------------------------------------------
 JoePass! is a program that animates juggling patterns. 
 It also provides some editors that let you write your own patterns.
 Copyright (C) <1997---today>  Wolfgang Westerboer
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 
 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 -----------------------------------------------------------------------*/
#include "graphics.h"

#include <stdio.h>


#include "openglmenu.h"
#include "inputWindow.h"


#define                         RunaroundInfoString					"runaround pattern, generated by JoePass!"
#define							RunaroundDelayFile					"runaroundDelayWalk_experimantal.pass"

#define							StdRunaroundProjectTitle			"main.pass"
#define							AnimatedRunaroundSceneInfoString	"animated runaround scene" 


#if defined(__cplusplus)
extern "C"
{
#endif
	
	extern bool						askForSaveInRunaround;
	bool							runaroundEditorHasOpenWindows(void );
	
	extern _menuList				*runaroundListMenuList;
	extern _menuList				*runaroundInputMenuList;
	
	extern int						numberOfRunaroundJugglers;
	extern char						runaroundProjectPath[];
	extern char						*runaroundProjectName;
	
	extern float					runaroundDelayWalk;
	extern int						defaultThrowForRunaroundPatterns;	
	extern int						animatedRunaroundSceneIndex;
	
	void							initRunaround( void );
	void							initRunaroundModule( void );
	void                            newRunaroundProject( void );
	void							openRunaroundProject( int dummy );
	void                            openRunaroundProjectFromBuffer( char *buf );
	void                            makeRunaroundEditorWindows( void );
	void							closeRunaroundNow( void );
	bool							openRunaroundProjectFromDirectory( char *dir );
	void							_closeRunaround( void );
	void							saveRunaroundProject( void );
	void							saveRunaroundProjectAs( void );
	void							releasePatternName( char *n);
	
	
	void                            runaroundTextOutput(GLfloat x, GLfloat y, float w, char *text);
	
	
	void							printRunaroundFieldContentToFile( FILE *fp, _fieldContent *p, int c);
	void							printRunaroundFieldContentToScreen( _fieldContent *l,  _fieldContent *f );
	void							saveCurrentRunaroundField( _fieldContent *currentField );
	void							readRunaroundFieldContent( _fieldContent *l );
	
	void                            initListModul( void );
	int                             getFieldIndex(_fieldContent *list, int entries, _fieldContent *f);
	
	void                            setRunaroundPatternChanged( wwwBoolean value );
	bool							getRunaroundPatternChanged( void );
	void                            writeAndStartRunaroundPattern(void);
	
	void                            redrawRunaroundWindows();
	
	
	void                            _selectPattern( void );
	void                            makeDefaultPattern( int jugglers );
	void                            addDefaultPattern( _fieldContent *list, int entries, _fieldContent *f );
	void                            _editPatternInCDEW( void );
	void                            _editPatternInTE( void );
	void							_doublePattern( void );
	void							_shrinkToHalve( void );
	
	bool							_openRunaroundProject( void );
	bool                            _openRunaroundProjectFromBuffer( char *buf );
#if defined(__cplusplus)
}
#endif
